### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by hobofan** [hobofan/collected-robotic-arms#6]
Before there are further contributions, a license should be chosen, as with any proper open source project.

One thing I'm not sure about is if the data in the repository (which is mostly taken from other websites) has to be licensed differently, or has to be marked as possibly copyrighted?

For the code, I'd probably go with "MIT OR Apache-2.0" as I usually do.

**Comment by gregsadetsky** [comment]
I'd vote for a very open data license, since this is a collection of facts that cannot be copyrighted -- this is as far as I understand & I am not a lawyer. :-)

**Comment by hobofan** [comment]
@gregsadetsky Yeah, I think you are right there. I think CC0 might be a good choice. I think we are not violating any copyright, since this project is extracting facts. But the project builds up a structured database, it might still qualify as copyrightable in certain jurisdictions, which is why I'm leaning towards marking it as CC0 instead of Public Domain. What do you think?

**Comment by gregsadetsky** [comment]
That sounds perfectly reasonable! From what I've read, it also seems like declaring a work to be PD is "problematic" (as the exact definition depends on the jurisdiction, etc.) which CC0 avoids.
